name: Build blog and publish
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: date; pwd; ls -l
      - run: make venv
      - run: make site
      - run: make publish
